name: Daily Pipeline

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Downgrade NumPy to pre-2.0
        run: pip install numpy==1.26.4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main script
        run: |
          python main_script.py

      - name: Configure Git
        run: |
          git config user.name "Amr Elsawalhi"
          git config user.email "amrelsawalhi@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/amrelsawalhi/DipSignal.git

      - name: Commit and Push CSVs
        run: |
          git add data/*.csv
          git commit -m "Auto-update CSVs from daily pipeline"
          git push origin master
