name: Daily Pipeline

on:
  schedule:
    - cron: '30 0 * * *'  # Every day at 00:30 UTC
  workflow_dispatch:      # Allow manual triggering

jobs:
  run-pipeline:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust to match your local env

      - name: Downgrade NumPy to pre-2.0
        run: pip install numpy==1.26.4
        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main script
        run: |
          python main_script.py

      - name: Configure Git for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit updated CSVs
        run: |
          git add data/*.csv
          git commit -m "Auto-update CSVs from daily pipeline"
          git push
