name: Daily Pipeline

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Downgrade NumPy to pre-2.0
        run: pip install numpy==1.26.4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main script
        run: |
          python main_script.py
      - name: Enable Git debug
        run: git config --global credential.helper '!echo username=oauth2 && echo password=$GH_PAT'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Amr Elsawalhi"
          git add data/*.csv
          git commit -m "Auto-update CSVs from daily pipeline"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/amrelsawalhi/DipSignal.git HEAD:master

